name: "Check PR labels"
description: "Check required PR labels are present"
author: "Replicated"
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  token:
    description: The GitHub token to use when calling the API
    default: ${{ github.token }}
    required: false
