name: Required pull request labels

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
    
jobs:
  check-labels:
    name: Check required PR labels are present
    runs-on: ubuntu-22.04
    steps:
    - uses: replicatedhq/required-workflows/.github/actions/pr-labels@main
